version: '3.8'

services:

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    container_name: postgres
    networks:
      - demo-network
    ports:
      - "5432:5432"
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      TABLE_NAME: $TABLE_NAME

    volumes:
      - postgres_data:/var/lib/postgresql/data


  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: flask-server
    networks:
      - demo-network
    ports:
      - "5000:5000"
    environment:
      API_KEY: $API_KEY
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME

networks:
  demo-network:
    external: true

volumes:
  postgres_data:
